version: '0.4.6.2 ({build})'

environment:
  ANDROID_HOME: C:\android-sdk-windows

install:
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
  - 7z x sdk-tools-windows-4333796.zip -oC:\android-sdk-windows > nul
  - yes | C:\android-sdk-windows\tools\bin\sdkmanager.bat --licenses > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "platforms;android-28" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "platform-tools" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "build-tools;28.0.3" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "cmake;3.6.4111459" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "patcher;v4" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "ndk-bundle" > nul
  - set PATH=%PATH%;C:\android-sdk-windows\ndk-bundle;C:\android-sdk-windows\build-tools\28.0.3

build_script:
  - gradlew.bat :edxp-core:zipYahfaRelease
  - gradlew.bat :edxp-core:zipSandhookRelease

artifacts:
  - path: 'edxp-core\release\**\*.zip'

pull_requests:
  do_not_increment_build_number: true

only_commits:
  files:
    - dalvikdx/
    - dexmaker/
    - edxp-common/
    - edxp-core/
    - edxp-sandhook/
    - edxp-whale/
    - edxp-yahfa/
    - hiddenapi-stubs/
    - xposed-bridge/
    - build.gradle
    - settings.gradle
    - gradle.properties
    - appveyor.yml